easy_admin:
   site_name: My admin
   design:
      menu: 
        - {entity: 'User', icon: 'user', permission: 'ROLE_ADMIN'}
        - {entity: 'Product', icon: 'home'}
   list:
      actions: ['show']
      collapse_actions: false
   entities:
      Product:
          class: App\Entity\Product
          list:
            sort: ['id', 'ASC']
            fields:
              - id
              - name
              - images
          form:
              fields:
                  - name
                  - 
                    property: images
                    type: 'App\Form\OrderType'
                    type_options: { required: false }
      User:
          class: App\Entity\User
          form:
              fields:
                  - username
                  - email
                  - enabled
                  - lastLogin
                  # if administrators are allowed to edit users' passwords and roles, add this:
                  - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                  - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

