parameters:
    app.path.product_images: /uploads/images/products

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/public/%app.path.product_images%'
